### PR TITLE
Upgrade vuln depDependencies mocha and jscs

### PR DESCRIPTION
**Pull request by joseluisbolos**

### CODE REVIEW

**Comment by umaar** [comment]
If we're upgrading mocha, could we check it still works? (Just in case they introduced some breaking changes)

**Comment by joseluisbolos** [comment]
The tests are all passing so I was assuming that was enough, is there anything else that would need to be tested?

**Comment by umaar** [comment]
Silly me, I missed that, looks good!

**Comment by joseluisbolos** [comment]
Merging this as we can safely ignore Bithound, it's being too strict.

**Pull request merged**
